export function onRequestGet(context) {
  const pc = ["pc/BA_pc (1).jpg","pc/BA_pc (1).png","pc/BA_pc (10).jpg","pc/BA_pc (10).png","pc/BA_pc (11).jpg","pc/BA_pc (11).png","pc/BA_pc (12).jpg","pc/BA_pc (12).png","pc/BA_pc (13).jpg","pc/BA_pc (13).png","pc/BA_pc (14).jpg","pc/BA_pc (14).png","pc/BA_pc (15).jpg","pc/BA_pc (15).png","pc/BA_pc (16).jpg","pc/BA_pc (16).png","pc/BA_pc (17).jpg","pc/BA_pc (17).png","pc/BA_pc (18).jpg","pc/BA_pc (18).png","pc/BA_pc (19).jpg","pc/BA_pc (19).png","pc/BA_pc (2).jpg","pc/BA_pc (2).png","pc/BA_pc (20).jpg","pc/BA_pc (20).png","pc/BA_pc (21).jpg","pc/BA_pc (21).png","pc/BA_pc (22).jpg","pc/BA_pc (22).png","pc/BA_pc (23).jpg","pc/BA_pc (24).jpg","pc/BA_pc (25).jpg","pc/BA_pc (26).jpg","pc/BA_pc (27).jpg","pc/BA_pc (28).jpg","pc/BA_pc (29).jpg","pc/BA_pc (3).jpg","pc/BA_pc (3).png","pc/BA_pc (30).jpg","pc/BA_pc (31).jpg","pc/BA_pc (32).jpg","pc/BA_pc (33).jpg","pc/BA_pc (34).jpg","pc/BA_pc (35).jpg","pc/BA_pc (36).jpg","pc/BA_pc (37).jpg","pc/BA_pc (38).jpg","pc/BA_pc (39).jpg","pc/BA_pc (4).jpg","pc/BA_pc (4).png","pc/BA_pc (40).jpg","pc/BA_pc (41).jpg","pc/BA_pc (42).jpg","pc/BA_pc (43).jpg","pc/BA_pc (44).jpg","pc/BA_pc (45).jpg","pc/BA_pc (46).jpg","pc/BA_pc (5).jpg","pc/BA_pc (5).png","pc/BA_pc (6).jpg","pc/BA_pc (6).png","pc/BA_pc (7).jpg","pc/BA_pc (7).png","pc/BA_pc (8).jpg","pc/BA_pc (8).png","pc/BA_pc (9).jpg","pc/BA_pc (9).png","pc/pixiv_pc (1).webp","pc/pixiv_pc (10).webp","pc/pixiv_pc (11).webp","pc/pixiv_pc (12).webp","pc/pixiv_pc (13).webp","pc/pixiv_pc (14).webp","pc/pixiv_pc (15).webp","pc/pixiv_pc (16).webp","pc/pixiv_pc (17).webp","pc/pixiv_pc (18).webp","pc/pixiv_pc (19).webp","pc/pixiv_pc (2).webp","pc/pixiv_pc (20).webp","pc/pixiv_pc (21).webp","pc/pixiv_pc (22).webp","pc/pixiv_pc (23).webp","pc/pixiv_pc (24).webp","pc/pixiv_pc (25).webp","pc/pixiv_pc (26).webp","pc/pixiv_pc (27).webp","pc/pixiv_pc (28).webp","pc/pixiv_pc (29).webp","pc/pixiv_pc (3).webp","pc/pixiv_pc (30).webp","pc/pixiv_pc (31).webp","pc/pixiv_pc (32).webp","pc/pixiv_pc (33).webp","pc/pixiv_pc (34).webp","pc/pixiv_pc (35).webp","pc/pixiv_pc (36).webp","pc/pixiv_pc (37).webp","pc/pixiv_pc (38).webp","pc/pixiv_pc (39).webp","pc/pixiv_pc (4).webp","pc/pixiv_pc (40).jpg","pc/pixiv_pc (5).webp","pc/pixiv_pc (6).webp","pc/pixiv_pc (7).webp","pc/pixiv_pc (8).webp","pc/pixiv_pc (9).webp"];
  const phone = ["phone/BA_ios (1).jpg","phone/BA_ios (1).png","phone/BA_ios (10).jpg","phone/BA_ios (10).png","phone/BA_ios (11).png","phone/BA_ios (12).png","phone/BA_ios (13).png","phone/BA_ios (14).png","phone/BA_ios (15).png","phone/BA_ios (16).png","phone/BA_ios (17).png","phone/BA_ios (18).png","phone/BA_ios (19).png","phone/BA_ios (2).jpg","phone/BA_ios (2).png","phone/BA_ios (20).png","phone/BA_ios (21).png","phone/BA_ios (22).png","phone/BA_ios (23).png","phone/BA_ios (24).png","phone/BA_ios (25).png","phone/BA_ios (26).png","phone/BA_ios (27).png","phone/BA_ios (28).png","phone/BA_ios (29).png","phone/BA_ios (3).jpg","phone/BA_ios (3).png","phone/BA_ios (30).png","phone/BA_ios (31).png","phone/BA_ios (33).png","phone/BA_ios (4).jpg","phone/BA_ios (4).png","phone/BA_ios (5).jpg","phone/BA_ios (5).png","phone/BA_ios (6).jpg","phone/BA_ios (6).png","phone/BA_ios (7).jpg","phone/BA_ios (7).png","phone/BA_ios (8).jpg","phone/BA_ios (8).png","phone/BA_ios (9).png","phone/pixiv_mob (1).webp","phone/pixiv_mob (10).webp","phone/pixiv_mob (11).webp","phone/pixiv_mob (12).webp","phone/pixiv_mob (13).webp","phone/pixiv_mob (14).webp","phone/pixiv_mob (15).webp","phone/pixiv_mob (16).webp","phone/pixiv_mob (2).webp","phone/pixiv_mob (3).webp","phone/pixiv_mob (4).webp","phone/pixiv_mob (5).webp","phone/pixiv_mob (6).webp","phone/pixiv_mob (7).webp","phone/pixiv_mob (8).webp","phone/pixiv_mob (9).webp"];
  const userAgent = context.request.headers.get("user-agent") || "";
  const isMobile = /mobile|android|iphone|ipad|ipod/i.test(userAgent);
  const list = isMobile ? phone : pc;
  const url = list.length > 0
    ? "https://random-picture.kafuchino.top/images/" + list[Math.floor(Math.random() * list.length)]
    : "https://random-picture.kafuchino.top/images/notfound.jpg";
  return Response.redirect(url, 302);
}